DeclarationIncident/AdminManager/Models/POCO/Incident.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AdminManager.Models.POCO
{
    public class Incident
    {
        public int idIncident { get; set; }
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Display(Name = "Titre")]
        public string imageTitle { get; set; }
        [Display(Name = "Chemin d'acces")]
        public string imagePath { get; set; }
        [Display(Name = "Date")]
        public string dateIncident { get; set; }

        [Display(Name = "Lieu")]
        public int idLocation { get; set; }
        [Display(Name = "Type d'incident")]
        public int idIncidentType { get; set; }
        [Display(Name = "Utilisateur")]
        public int idUser { get; set; }
        [Display(Name = "Statut ")]
        public int IdIncidentStatut { get; set; }

        public virtual Location Location { get; set; }
        public virtual User user { get; set; }
        public virtual IncidentType incidentType { get; set; }
        public virtual IncidentStatut incidentState { get; set; }

        public virtual List<Comment> comment { get; set; }
        public virtual List<Notification> notification { get; set; }

    }
}

DeclarationIncident/AdminManager/Models/POCO/IncidentType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AdminManager.Models.POCO
{
    public class IncidentType
    {
        public int idIncidentType { get; set; }
        public string Libelle { get; set; }
        [Display(Name = "Titre"),Required]
        public string imageTitle { get; set; }
        [Display(Name = "Lien"),Required]
        public string imagePath { get; set; }
    }
}

DeclarationIncident/AdminManager/Controllers/IncidentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AdminManager.Models.POCO;
using AdminManager.Models.Services;
using AdminManager.Models.ViewModel;

namespace AdminManager.Controllers
{
    //[Authorize]
    public class IncidentController : Controller
    {
        IncidentServices incidentServices = new IncidentServices();
        IncidentVM incidentVm = new IncidentVM();


        // Affiche la vue principale
        public ActionResult Index()
        {
            return View();
        }

        /*
         * Affiche la vue partielle
         * toute les 10 secondes un appel
         * ajax effectue une mis à jour périodique
         */
        public async Task<ActionResult> _GetIncidentList()
        {
            var result = await incidentServices.GetIncidentAsync();
            var model = new List<IncidentVM>();

            foreach (var items in result)
            {
                model.Add(
                    new IncidentVM()
                    {
                        idIncident = items.idIncident,
                        Description = items.Description,
                        dateIncident = items.dateIncident,
                        incidentType = items.incidentType,
                        Location = items.Location,
                        incidentStatut = items.incidentState,
                        IdIncidentState = items.IdIncidentStatut,
                        //statuName = items.incidentState.description,
                        user = items.user
                    });
            }

            if (model != null)
                return PartialView("_GetIncidentList",model);
          
            return HttpNotFound();
        }

        [HttpGet]
        public async Task<ActionResult> Detail(int id = 0)
        {
            if (id > 0)
            {
                var userInfo =await incidentServices.GetEntityById(id);

                if (userInfo != null)
                {
                    var details = new IncidentVM()
                    {
                        idIncident = userInfo.idIncident,
                        Description = userInfo.Description,
                        dateIncident = userInfo.dateIncident,
                        incidentStatut = userInfo.incidentState,
                        imageTitle = userInfo.imageTitle
                    };
                    return View(details);
                }
                    return null;
            }

            return View("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int id = 0)
        {
            if (id > 0)
            {
                var deleteIncident =await incidentServices.DeleteIncident(id);

                if (deleteIncident == true)
                    return RedirectToAction("Index");
                return HttpNotFound();
            }
            return View("Index");
        }

        /*
         * Affiche le statut de l'insident
         */
        public async Task<ActionResult> ToDoTaskStatStatut(int id)
        {
            //
            if (id > 0)
            {
                var toDoTaskStateServices = new ToDoTaskStateServices();

                var model = await toDoTaskStateServices.GetEntityById(id);
             
                if (model != null)
                    return PartialView("_TaskStatut",model);

                return PartialView("_TaskStatut", model.description = "En attente" );
            }
            return RedirectToAction("Index");
        }

        
        /*
         *
         */
        //public ActionResult _CreateNotification(int id)
        //{
        //    var notificationType = new NotificationTypeServices();

        //    if (id > 0)
        //    {
        //        var model = new NotificationVM()
        //        {
        //            idIncident = id,
        //            ListNotificationTypes = notificationType.GetAllNotificationType()
        //        };
        //        var mod = model;
        //        return PartialView(model);
        //    }

        //    return null;
        //}
    }
}

DeclarationIncident/AdminManager/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AdminManager.Models.POCO;
using AdminManager.Models.Services;
using AdminManager.Models.ViewModel;

namespace AdminManager.Controllers
{
    public class NotificationController : Controller
    {
      NotificationServices notificationServices = new NotificationServices();

        // GET: Notification
            public ActionResult _Create(int id)
            {
                if (id > 0)
                {
                    var model = new NotificationVM()
                    {
                        idIncident = id,
                    };
            
                    return PartialView(model);
                }
                return null;
            }

            [HttpPost]
            public ActionResult Create(Notification model)
            {
                if (ModelState.IsValid)
                {
                    var result = notificationServices.CreateNotification(model);
                    return RedirectToAction("Index","Incident");
                }
                return RedirectToAction("Index", "Incident");
            }

            public ActionResult Notification(int id = 0)
            {
                var model = new List<Notification>();
                if (id > 0)
                {
                    model = notificationServices.GetAllNotification().Where(u => u.idIncident == id).ToList();
                }
                
                return PartialView("_Notification", model);
            }
    }
}

DeclarationIncident/AdminManager/Controllers/ToDoTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AdminManager.Models.POCO;
using AdminManager.Models.Services;
using AdminManager.Models.ViewModel;

namespace AdminManager.Controllers
{
    public class ToDoTaskController : Controller
    {
        ToDoTaskVM model = new ToDoTaskVM();
        ToDoTaskServices toDoTaskServices = new ToDoTaskServices();

        // GET: ToDoTask
        [HttpGet]
        public async Task<ActionResult> Create(string incidentDescription, string incidentLocation, int id = 0)
        {
            if (id > 0)
            {
                var adminServices = new AdminServices();
                model = new ToDoTaskVM()
                {
                    UsersList = await adminServices.GetAllUserAsync(), //List de tout les utilisateurs
                    idIncident = id,
                    incidentDescription = incidentDescription,
                    incidentLocation = incidentLocation
                };
                return PartialView(model);
            }
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(ToDoTask model)
        {
            if (ModelState.IsValid)
            {
                model.dateTask = DateTime.Now;
                var createTaskToDo =await toDoTaskServices.CreateToDoTaskServices(model);

                if (createTaskToDo)
                    return RedirectToAction("Index", "Incident");
                return HttpNotFound();
            }
            return View();
        }

    }
}

DeclarationIncident/AdminManager/Views/Incident/Detail.cshtml
@model AdminManager.Models.ViewModel.IncidentVM

@{
    ViewBag.Title = "Detail Incident";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>

</head>
<body>
    
<h2>Detail</h2>

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            
            <hr/>
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.dateIncident)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.dateIncident)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Location.nameLocation)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Location.nameLocation)
                </dd>

            </dl>
        </div>
        <div class="col-md-4">
            <dl>
                <dd>
                    @*@Html.DisplayFor(model => model.imagePath)*@
                    @{
                        var base64 = Convert.ToBase64String(Model.GetFile(Model.imageTitle));
                        var imgrc = string.Format("data:image/jpg;base64,{0}", base64);

                        <img class="img-thumbnail" src="@imgrc" style="max-width: 200px;height: 200px" />
                        @Html.DisplayFor(modelItem => Model.imageTitle)
                    }
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        @Html.Action("_Create", "Notification", new {id = Model.idIncident});
    </div>

</div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

DeclarationIncident/AdminManager/Views/Incident/Index.cshtml
@using AdminManager.Models.POCO
@model IEnumerable<AdminManager.Models.ViewModel.IncidentVM>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

@*Vue partielle*@
<div id="refreshme">

</div>

<div class="modal fade" id="myModal"></div>

<script type="text/javascript">

        var timer;

        $(function() {
            GetIncidentTaskState();
            timer = window.setInterval("GetIncidentTaskState()", 10000)
        })

    function GetIncidentTaskState() {
        $.ajax({
            url: "@Url.Action("_GetIncidentList", "Incident")",
            type: 'GET',
            dataType: 'html',
            success: function(result) {
                $('#refreshme').html(result);
            }
        });
    }

</script>
</body>
</html>

DeclarationIncident/AdminManager/Views/Incident/_GetIncidentList.cshtml
@model IEnumerable<AdminManager.Models.ViewModel.IncidentVM>


<html>
<head>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
<p>
    <a href="@Url.Action("Nouveau", "Create")" class="btn btn-primary btnLink">
        Nouveau
        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
    </a>
</p>
    <table class="table table-bordered" id="refreshme">
        <thead class="alert-info">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.incidentType.Libelle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.dateIncident)
                </th>
                <th>
                    Statut
                </th>
                <th colspan="3" style="text-align: center">Action</th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.nameLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dateIncident)
                </td>
                <td>
                    <div id="refreshme">
                        @item.IdIncidentState
                    </div>
                </td>
                <td>
                    <a data-url="@Url.Action("Create", "ToDoTask", new { id=@item.idIncident, incidentDescription = @item.Description,
                                 incidentLocation = @item.Location.nameLocation })" class="btn btn-info btnLink activePopUp" role="dialog">
                        Traiter
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Detail", "Incident", new {id = @item.idIncident })" class="btn btn-info btnLink" data-id="@item.idIncident">
                        Detail
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Delete", "Incident", new {id = @item.idIncident})" class="btn btn-danger btnLink">
                        Supprimer
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>
                </td>
            </tr>
        }
    </table>

    <div class="modal fade" id="myModal"></div>

    <script type="text/javascript">
        $(document).ready(function () {

            $('.activePopUp').click(function (event) {
                event.preventDefault();

                var url = $(this).data('url');
                console.log(url)

                $.get(url,
                    function (data) {

                        $('#myModal').html(data);
                        $('#myModal').modal('show');
                    });
            });
        });

    </script>
</body>
</html>

DeclarationIncident/AdminManager/Views/Incident/_TaskStatut.cshtml
@model AdminManager.Models.POCO.IncidentStatut

<div>
     @{
        var x = Model.IdIncidentStatut;

     }
     Numm
        @Model.incident
 </div>