DeclarationIncident/AdminManager/Controllers/IncidentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AdminManager.Models.POCO;
using AdminManager.Models.Services;
using AdminManager.Models.ViewModel;

namespace AdminManager.Controllers
{
    //[Authorize]
    public class IncidentController : Controller
    {
        IncidentServices incidentServices = new IncidentServices();
        IncidentVM incidentVm = new IncidentVM();


        // Affiche la vue principale
        public ActionResult Index()
        {
            return View();
        }

        /*
         * Affiche la vue partielle
         * toute les 10 secondes un appel
         * ajax effectue une mis à jour périodique
         */
        public async Task<ActionResult> _GetIncidentList()
        {
            var result = await incidentServices.GetIncidentAsync();
            var model = new List<IncidentVM>();

            foreach (var items in result)
            {
                model.Add(
                    new IncidentVM()
                    {
                        idIncident = items.idIncident,
                        Description = items.Description,
                        dateIncident = items.dateIncident,
                        incidentType = items.incidentType,
                        Location = items.Location,
                        incidentStatut = items.incidentState,
                        IdIncidentState = items.IdIncidentStatut,
                        //statuName = items.incidentState.description,
                        user = items.user
                    });
            }

            if (model != null)
                return PartialView("_GetIncidentList",model);
          
            return HttpNotFound();
        }

        [HttpGet]
        public async Task<ActionResult> Detail(int id = 0)
        {
            if (id > 0)
            {
                var userInfo =await incidentServices.GetEntityById(id);

                if (userInfo != null)
                {
                    var details = new IncidentVM()
                    {
                        idIncident = userInfo.idIncident,
                        Description = userInfo.Description,
                        dateIncident = userInfo.dateIncident,
                        incidentStatut = userInfo.incidentState,
                        imageTitle = userInfo.imageTitle
                    };
                    return View(details);
                }
                    return null;
            }

            return View("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int id = 0)
        {
            if (id > 0)
            {
                var deleteIncident =await incidentServices.DeleteIncident(id);

                if (deleteIncident == true)
                    return RedirectToAction("Index");
                return HttpNotFound();
            }
            return View("Index");
        }

        /*
         * Affiche le statut de l'insident
         */
        public async Task<ActionResult> ToDoTaskStatStatut(int id)
        {
            //
            if (id > 0)
            {
                var toDoTaskStateServices = new ToDoTaskStateServices();

                var model = await toDoTaskStateServices.GetEntityById(id);
             
                if (model != null)
                    return PartialView("_TaskStatut",model);

                return PartialView("_TaskStatut", model.description = "En attente" );
            }
            return RedirectToAction("Index");
        }

        
        /*
         *
         */
        //public ActionResult _CreateNotification(int id)
        //{
        //    var notificationType = new NotificationTypeServices();

        //    if (id > 0)
        //    {
        //        var model = new NotificationVM()
        //        {
        //            idIncident = id,
        //            ListNotificationTypes = notificationType.GetAllNotificationType()
        //        };
        //        var mod = model;
        //        return PartialView(model);
        //    }

        //    return null;
        //}
    }
}

DeclarationIncident/AdminManager/Controllers/IncidentTypeController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AdminManager.Models.POCO;
using AdminManager.Models.Services;
using AdminManager.Models.ViewModel;

namespace AdminManager.Controllers
{
    //[Authorize]
    public class IncidentTypeController : Controller
    {
        IncidentTypeServices services = new IncidentTypeServices();
        static HttpClient client = new HttpClient();

        // GET: IncidentType
        public async Task<ActionResult> Index()
        {
            var listInc = new List<IncidentTypeVM>();
            var listItem = await services.GetAllIncidentTypeAsync();

            foreach (var items in listItem)
            {
                listInc.Add(
                    new IncidentTypeVM()
                    {
                        Libelle = items.Libelle,
                        imageTitle = items.imageTitle,
                        imagePath = items.imagePath,
                        idIncidentType = items.idIncidentType
                    });
                }

            return View(listInc);
        }

        [HttpGet]
        public ActionResult CreateIncidentType()
        {
            return View();
        }

       [HttpPost]
        public async Task<ActionResult> CreateIncidentType(IncidentType model)
        {
            //byte[] bytes;
            //using (BinaryReader br = new BinaryReader(imageFile.InputStream))
            //{
            //    bytes = br.ReadBytes(imageFile.ContentLength);
            //}

            ////
            //IncidentType entities = new IncidentType()
            //{
            //    imagePath = Path.GetFileName(imageFile.FileName),
            //    Libelle = model.Libelle,
            //    imageTitle = imageFile.ContentType,
            //    fileContent = bytes,
            //    idUser = 1
            //};
            
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                
                var content = new MultipartFormDataContent();

                byte[] fileBytes = new byte[file.InputStream.Length + 1];
                file.InputStream.Read(fileBytes, 0, fileBytes.Length);

                var fileContent = new ByteArrayContent(fileBytes);
               fileContent.Headers.ContentDisposition = new System.Net.Http.Headers.ContentDispositionHeaderValue("attachment") { FileName = file.FileName };


                //content.Add(new StreamContent(fileContent,
                //    "\"file\"",
                //    $"\"{fileContent.p.Path}\"");

                content.Add(fileContent);

                model.imageTitle = file.FileName;
                var result = await services.CreateIncidentType(model, content);

                //
                if (result)
                    return RedirectToAction("Index");
                return View(model);
            }

            return null;

            //var content = new MultipartFormDataContent();

            //content.Add(new StreamContent(mediaFile.gets),
            //    "\"file\"",
            //    $"\"{mediaFile.Path}\"");


        }

        public async Task<ActionResult> DeleteIncidentType(int id)
        {
            if (id > 0)
            {
                var result = await services.DeleteById(id);
                if (result)
                    return RedirectToAction("Index");
            }
            return View();
        }
    }
}

DeclarationIncident/AdminManager/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AdminManager.Models.POCO;
using AdminManager.Models.Services;

namespace AdminManager.Controllers
{
    //[Authorize]
    public class LocationController : Controller
    {
        // GET: Location
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> ListAsync()
        {
            var items = new LocationServices();
            var listedLocations =await items.GetLocationAsync();
        
            return Json(listedLocations, JsonRequestBehavior.AllowGet);
        }

        // GET: Location
        [HttpPost]
        public async Task<ActionResult> CreateLocation(Location location)
        {
            if (ModelState.IsValid)
            {
                var locationServices = new LocationServices();

                //
                var task = locationServices.CreateLocationAsync(location);
                await task;
                if (task.Exception !=null)
                    ModelState.AddModelError("","Unable to add the asset ");
                return View("Index");
            }

            return null;
        }
    }
}

DeclarationIncident/AdminManager/Controllers/UserCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AdminManager.Models.POCO;
using AdminManager.Models.Services;

namespace AdminManager.Controllers
{
    //[Authorize]
    public class UserCategoryController : Controller
    {
        private RoleServices roleServices = new Models.Services.RoleServices();

        [HttpGet]
        public async Task<ActionResult> Index()
        {
           var ListCategory = await roleServices.GetAllCategoryAsync();

            if(ListCategory !=null )
                return View( ListCategory);
            return HttpNotFound();
        }

        public ActionResult _CreateCategory()
        {
            return PartialView("_CreateCategory");
        }

        [HttpPost]
        public async Task<ActionResult> Create(Models.POCO.Role model)
        {
            if (ModelState.IsValid)
            {
                var result = await roleServices.CreateCategoryAsinc(model);

                if (result)
                {
                    return RedirectToAction("Index");
                }
                return HttpNotFound();
            }
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> DeleteCategory(int id = 0)
        {
            if (id > 0)
            {
                var isDelete =await roleServices.DeleteCategory(id);

                if (isDelete)
                    return RedirectToAction("Index");
                return HttpNotFound();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> EditCategory(int id = 0)
        {
            if (id > 0)
            {
                var getCategory = await roleServices.GetEntityById(id);
                return View("_CreateCategory", getCategory);
            }

            return RedirectToAction("Index");
        }
    }
}

DeclarationIncident/AdminManager/Views/Shared/_DropDownListCategory.cshtml
@model AdminManager.Models.ViewModel.CategoryVM
    
<div class="form-group">
    @Html.LabelFor(model => model.idUserCategory, "idUserCategory", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownListFor(model => model.idUserCategory, new SelectList(Model.categories, "idUserCategory", "userCategory1"), "-- Liste des clients --", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.idUserCategory, "", new { @class = "text-danger" })
    </div>
</div>

DeclarationIncident/AdminManager/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

DeclarationIncident/AdminManager/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

DeclarationIncident/AdminManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        </button>
       
        @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <div class="navbar-collapse collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav mr-auto">
                <li>
                    <a href="@Url.Action("Index", "IncidentType")" class="nav-link">
                        <span class="glyphicon glyphicon-home"></span>
                        Categorie d'incident
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "UserCategory")" class="nav-link">
                        <span class="glyphicon glyphicon-home"></span>
                        Catégorie utilisateur
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Location")" class="nav-link">
                        <span class="glyphicon glyphicon-home"></span>
                        Lieux
                    </a>
                </li>
                @*<li>
                    <a href="@Url.Action("Index", "Home")" class="nav-link">
                        <span class="glyphicon glyphicon-home"></span>
                        Utilisateur
                    </a>
                </li>*@
                <li>
                    <a href="@Url.Action("Index", "Incident")" class="nav-link">
                        <span class="glyphicon glyphicon-home"></span>
                        Incident
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right mr-auto">
               @{
                    if ((string) Session["userName"] != null)
                    {
                    <a href="#" class="nav-link">
                        @Session["userName"].ToString()
                    </a>
                    }
                }
            </ul>

        </div>
    </div>
</nav>
<div class="container body-content">
    <div>
        <br/>
    </div>
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Gestion d'incident </p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/gridmvc")
    @RenderSection("scripts", required: false)
</body>
</html>